babys/babys/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('index.urls', 'index'), namespace='index')),
    path('commodity', include(('commodity.urls', 'commodity'), namespace='commodity')),
    path('shopper', include(('shopper.urls', 'shopper'), namespace='shopper')),
    re_path('media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
]

babys/commodity/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    # path('.html', commodityView, name='commodity'),
    # path('/detail.<int:id>.html', detailView, name='detail'),
]

babys/index/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    # path('', indexView, name='index',),
    path('', indexClassView.as_view(), name='index'),
]

babys/shopper/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    # path('.html', shopperView, name='shopper'),
    # path('/login.html', loginView, name='login'),
    # path('/logout.html', logoutView, name='logout'),
    # path('/shopcart.html', shopcartView, name='shopcart'),
]

babys/commodity/models.py
from django.db import models

# Create your models here.


class Types(models.Model):
    id = models.AutoField(primary_key=True)
    firsts = models.CharField('一级类型', max_length=100)
    seconds = models.CharField('二级类型', max_length=100)

    def __str__(self):
        return str(self.id)


class Meta:
    verbose_name = '商品类型'
    verbose_name_plural = '商品类型'


class CommodityInfos(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField('商品名称', max_length=100)
    eszes = models.CharField('颜色规格', max_length=100)
    types = models.CharField('商品类型', max_length=100)
    price = models.FloatField('商品价格')
    discount = models.FloatField('折扣价格')
    stock = models.IntegerField('存货数量')
    sold = models.IntegerField('已售数量')
    likes = models.IntegerField('收藏数量')
    created = models.DateField('上架日期', auto_now_add=True)
    img = models.FileField('商品主图', upload_to=r'imgs')
    dails = models.FileField('商品介绍', upload_to=r'details')

    def __str__(self):
        return str(self.id)


    class Meta:
        verbose_name = '商品信息'
        verbose_name_plural = '商品信息'

babys/index/models.py
from django.db import models

# Create your models here.


class PersonInfo(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=20)
    age = models.IntegerField(null=True)
    hireDate = models.DateField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '人员信息'


class Vocation(models.Model):
    id = models.AutoField(primary_key=True)
    job = models.CharField(max_length=20)
    title = models.CharField(max_length=20)
    payment = models.IntegerField(null=True, blank=True)
    name = models.ForeignKey(PersonInfo, on_delete=models.CASCADE, related_name='ps')

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = '职业信息'


#省份
class Province(models.Model):
    name = models.CharField(max_length=10)

    def __str__(self):
        return str(self.name)


# 城市
class City(models.Model):
    name = models.CharField(max_length=20)
    province = models.ForeignKey(Province, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.name)


# 人物
class Person(models.Model):
    name = models.CharField(max_length=20)
    living = models.ForeignKey(City, on_delete=models.CASCADE)
    
    def __str__(self):
        return str(self.name)


# 员
class Performer(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=20)
    nationality = models.CharField(max_length=20)

    def __str__(self):
        return str(self.name)


# 节目
class Program(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=20)
    performer = models.ManyToManyField(Performer)
    
    def __str__(self):
        return str(self.name)

babys/shopper/models.py
from django.db import models

# Create your models here.


STATE = (
    ('待支付', '待支付'),
    ('已支付', '已支付'),
    ('发货中', '发货中'),
    ('已签收', '已签收'),
    ('退货中', '退货中'),
)


class CartInfos(models.Model):
    id = models.AutoField(primary_key=True)
    quantity = models.IntegerField('购买数量')
    commodityInfos_id = models.IntegerField('商品ID')
    user_id = models.IntegerField('用户ID')

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = '购物车'
        verbose_name_plural = '购物车'


class OrderInfos(models.Model):
    id = models.AutoField(primary_key=True)
    price = models.FloatField('订单总价')
    created = models.DateField('创建时间', auto_now_add=True)
    user_id = models.IntegerField('用户ID')
    state = models.CharField('订单状态', max_length=20, choices=STATE)

    def __str__(self):
        return str(self.id)


    class Meta:
        verbose_name = '订单信息'
        verbose_name_plural = '订单信息'

babys/commodity/views.py
from django.shortcuts import render

# Create your views here.

babys/index/views.py
from django.shortcuts import render
from commodity.models import *
from index.models import PersonInfo
from django.views.generic.base import TemplateView
# Create your views here.


# def indexView(request):
#     title = '首页'
#     classContent = ''
#     commodityInfos =CommodityInfos.objects.oerder_by('-sold').all()[:8]

#     types = Types.objects.all()
#     # 宝宝服饰dfdsfk
#     c1 = [x.seconds for x in types if x.firsts == '儿童服饰']
  
#     clothes = CommodityInfos.objects.filter(types_in=c1).order_by('-sold')[:5]
    
#     # 奶粉辅食
#     f1 = [x.seconds for x in types if x.firsts == '奶粉辅食']
#     food = CommodityInfos.objects.filter(types__in=f1).order_by('-sold')[0:5]

#     # 宝宝用品
#     g1 = [x.seconds for x in types if x.firsts == '儿童用品']
#     goods = CommodityInfos.objects.filter(types__in=g1).order_by('-sold')[:5]
     
#     return render(request, 'index.html', locals())


# def indexView(request):
#     # 使用method属性判断请求方式
#     if request.method == 'GET':
#         # 类方法的使用
#         print(request.is_secure())
#         print(request.is_ajax())
#         print(request.get_host())
#         print(request.get_full_path())
#         print(request.get_raw_url())
#         # 属性的使用
#         print(request.COOKIES)
#         print(request.content_type)
#         print(request.content_params)
#         print(request.scheme)
#         # 获取get请求的请求参数
#         print(request.GET.get('user',''))

#         return render(request, 'index.html')

#     elif request.method == 'POST':
#         # 获取post请求的请求参数
#         print(request.POST.get('user',''))
#         return render(request, 'index.html')

class indexClassView(TemplateView):
    template_name = 'index.html'
    template_engine = None
    content_type = {'title':'首页', 'classContent':''}

    # 重新定义模板上下文的获取方式
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['commodityInfos'] = CommodityInfos.objects.order_by('-sold').all()[:8]
        types = Types.objects.all()
        
        # 宝宝服饰
        c1 = [x.seconds for x in types if x in x.firsts == '儿童服饰']
        context['clothes'] = CommodityInfos.objects.filter(types__in=c1).order_by('-sold')[:5]

        # 奶粉辅食
        f1 = [x.seconds for x in types if x in x.firsts == '奶粉辅食']
        context['food'] =  CommodityInfos.objects.filter(types__in=f1).order_by('-sold')[:5]

        # 宝宝用品
        g1 = [x.seconds for x in types if x in x.firsts == '儿童用品']
        context['goods'] = CommodityInfos.objects.filter(types__in=g1).order_by('-sold')[:5]

        return context
    
    def get(self, request, *args, **kwargs):
        pass
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        pass
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)


        

babys/shopper/views.py
from django.shortcuts import render

# Create your views here.

babys/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <!-- 1 -->
        {% load static %}
        <title>{{title}}</title>
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" href="{% static 'layui/css/layui.css' %}">
        <script src="{% static 'layui/layui.js' %"></script>
    </head>
    <body>
        <div class="header">
            <div class="headerLayout w1200">
                <div class="headerCon">
                    <!-- 2 -->
                    <h1 class="mallLogo">
                        <a href="{% url 'index:index' %}" title="母婴商城">
                            <img src="{% static 'img/logo.png' %}" alt="">
                        </a>
                        
                    </h1>
                    <!-- 3 -->
                    <div class="mallSearch">
                        <form action="{% url 'commodity:commodity' %}" method="GET" class="layui-form" novalidate>
                            <input type="text" name="n" required lay-verify="required" autocomplete="off" class="layui-input" placeholder="请输入需要的商品">
                            <button class="layui-btn" lay-submit lay-filter="formDemo">
                                <i class="layui-icon layui-icon-search"></i>
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="content content-nav-base {{classContent}}">
            <div class="main-nav">
                <div class="inner-cont0">
                    <div class="inner-cont1 w1200">
                        <!-- 4 -->
                        <div class="inner-cont2">
                            <a href="{% url 'index:index' %}" {% if classContent == '' %}class="active"{% endif %}>首页</a>
                            <a href="{% url 'commodity:commodity' %}" {% if classContent == 'commoditys' %} class="active"{% endif %}>所有商品</a>
                            <a href="{% url 'shopper:shopper' %}" {% if classContent == 'shopcarts' %} class="active" {% endif %}>购物车</a>
                            <a href="{% url 'shopper:shopper' %}" {% if classContent == 'informations' %}class="active"{% endif %}>个人中心</a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- 5 -->
            {% block content %}{% endblock content %}
        </div>
        {% block footer %}{% endblock footer %}
        <script type="text/javascript">
            {% block script %}{% endblock script %}
        </script>
    </body>
</html>

babys/templates/commodity.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

babys/templates/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

babys/templates/index.html
<!-- 1 -->
{%  extends 'base.html' %}
{%  load static %}
{% comment %} 2 {% endcomment %}
{% block content %}
<div class="category-con">
    <div class=c"category-banner">
        <div class="w1200">
            <img src="{% static 'img/banner1.jpg' %}">
        </div>
    </div>
</div>

{% comment %} 3 {% endcomment %}
<div class="floors">
    <div class="sk">
        <div class="sk-inner w1200">
            <div class="sk_hd">
                <a href="javascript:;">
                    <img src="{% static 'img/s_img1.jpg' %}" alt="">
                </a>
            </div>
            <div class="sk_bd">
                <div class="layui-carousel" id="test1">
                    <div carousel-item>
                        <div class="item-box">
                            {% for c in commodityInfos %}
                                {% if forloop.counter < 5 %}
                                <div class="item">
                                    <a href="{% url 'commodity:detail' c.id %">
                                        <img src="{{ c.img.url }}" alt="">
                                    </a>
                                    <div class="title">
                                        {{ c.name }}
                                    </div>
                                    <div  class="price">
                                        <span>$ {{ c.discount|floatformat:'2' }}</span>
                                        <del>$ {{ c.price|floatformat:'2' }}</del>
                                    </div>
                                </div>
                                {% endif %}
                            {% endfor %}
                        </div>
                        <div class="item-box">
                            {% for c in commodityInfo %}
                                {% if forloop.counter > 4 %}
                                <div class="item">
                                    <a herf="{% url 'commodity:detail' c.id %}"><img src="{{ c.img.url }}"> </a>
                                    <div class="title">{{ c.name }}</div>
                                    <div class="price">
                                        <span>${{ c.discount|floatformat:'2' }}</span>
                                        <del>${{ c.price|floatformat:'2' }}</del>
                                    </div>
                                </div>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--4-->
<div class="product-cont w1200" id="product-cont">
    <div class="product-item product-item1 layui-clear">
        <div class="left-title">
            <h4><i>1F</i></h4>
            <img src="{% static 'img/icon_gou.jpg' %}">
            <h5>宝宝服饰</h5>
        </div>
        <div class="right-cont">
            <a herf="javascript:;" class="top-img">
                <img src="{% static 'img/img12.jpg' %}" alt="">
            </a>
            <div class="img-box">
                 {% for c in clothes %}
                 <a href="{% url 'commodity:detail' c.id %}">
                     <img src="{{ c.img.url }}">
                 </a>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="product-item product-item2 layui-clear">
        <div class="left-title">
            <h4><i>2F</i></h4>
            <img src="{% static 'img/icon_gou.png' %}">
            <h5>奶粉辅食</h5>
        </div>
        <div class="right-cont">
            <a href="javascript:;" class="top-img">
                <img src="{% static 'img/img12.jpg' %}" alt="">
            </a>
            <div class="img-box">
                {% for f in food %}
                <a href="{% url 'conmodity:detail' f.id %}">
                    <img src="{{ f.img.url }}">
                </a>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="product-item product-item3 layi-clear">
        <div class="left-tittle">
            <h4><i>3F</i></h4>
            <img src="{% static 'img/icon_gou.png' %}">
            <h5>宝宝用品</h5>
        </div>
        <div class="right-cont">
            <a href="javascript:;" class="top-img">
                <img src="{% static 'img/img12.jpg' %}">
            </a>
            <div class="img-box">
                {% for g in goods %}
                <a href="{% url 'commodity:detail' g.id %}">
                    <img src="{% g.img.url %}">
                </a>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}
<!--5-->
{% block footer %}
<div class="footer">
    <div class="ng-promiss-box">
        <div class="ng-promise w1200">
            <p class="text">
                <a class="icon1" href="javascript:;">7天无理由退换货</a>
                <a class="icon2" href="javascript:;">满99元全场免费</a>
                <a class="icon3" style="margin-right" href="javascript:;">100%品质保证</a>
            </p>
        </div>
    </div>
    <div class="mod-help w1200">
        <p>
            <a href="javascript:;">关于我们</a>
            <span>|</span>
            <a href="javascript:;">帮助中心</a>
            <span>|</span>
            <a href="javascript:;">售后服务</a>
            <span>|</span>
            <a href="javascript:;">母婴咨询</a>
            <span>|</span>
            <a href="javascript:;">关于货源</a>
        </p>
    </div>
</div>
{% endblock footer %}

{% block script %}
layui.config({
    base: '{% static 'js/' %}'}).use(['mm','carouse1'],function(){
        var carousel = layui.carouse1,
        mm = layui.mm;
        var option = {
            elem: '#test1'
            ,width: '100%'
            ,arrow: 'always'
            ,indicator:'none'
        }
        carouse1.render(option);
})
{% endblock script %}

babys/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

babys/templates/shopcart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

babys/templates/shopper.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>